"""add shipping and payment fields to orders

Revision ID: 174650b2dc9c
Revises: 2b9c6fb23480
Create Date: 2026-09-13 13:45:42.962723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '174650b2dc9c'
down_revision: Union[str, Sequence[str], None] = '2b9c6fb23480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tryon_jobs_id'), table_name='tryon_jobs')
    op.drop_table('tryon_jobs')
    op.add_column('orders', sa.Column('customer_name', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('customer_email', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('customer_phone', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('shipping_address', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'customer_phone')
    op.drop_column('orders', 'customer_email')
    op.drop_column('orders', 'customer_name')
    op.create_table('tryon_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_photo_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fitroom_job_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('tryon_jobs_product_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('tryon_jobs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tryon_jobs_pkey'))
    )
    op.create_index(op.f('ix_tryon_jobs_id'), 'tryon_jobs', ['id'], unique=False)
    # ### end Alembic commands ###
