"""add delivery charge to orders

Revision ID: 982cf42a07fc
Revises: 174650b2dc9c
Create Date: 2026-09-13 14:16:53.612849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982cf42a07fc'
down_revision: Union[str, Sequence[str], None] = '174650b2dc9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('delivery_charge', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'delivery_charge')
    # ### end Alembic commands ###
