"""add image_urls to products

Revision ID: b6a22c4c2b93
Revises: 39d1939cd635
Create Date: 2026-09-13 20:31:11.537223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a22c4c2b93'
down_revision: Union[str, Sequence[str], None] = '39d1939cd635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_urls', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_urls')
    # ### end Alembic commands ###
