"""move delivery charge to order

Revision ID: ccb589077099
Revises: c16d73c9e719
Create Date: 2026-09-13 23:09:23.216702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb589077099'
down_revision: Union[str, Sequence[str], None] = 'c16d73c9e719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'delivery_charge')
    op.add_column('orders', sa.Column('delivery_charge', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_charge')
    op.add_column('order_items', sa.Column('delivery_charge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
